# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "manager01" do |manager|
    manager.vm.box = "ubuntu/jammy64"
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.50"
    config.vm.network "forwarded_port", guest: 9090, host: 9090, auto_correct: true  # Prometheus
    config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true  # Grafana
    config.vm.network "forwarded_port", guest: 3100, host: 3100, auto_correct: true  # Loki
    config.vm.network "forwarded_port", guest: 9100, host: 9100, auto_correct: true  # Node Exporter
    config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true  # cAdvisor
    config.vm.network "forwarded_port", guest: 9115, host: 9115, auto_correct: true  # Blackbox
    config.vm.network "forwarded_port", guest: 8087, host: 8087, auto_correct: true  # Gateway Service
    config.vm.network "forwarded_port", guest: 8081, host: 8081, auto_correct: true  # Session Service  
    config.vm.network "forwarded_port", guest: 8082, host: 8082, auto_correct: true  # Hotel Service
    config.vm.network "forwarded_port", guest: 8083, host: 8083, auto_correct: true  # Booking Service
    config.vm.network "forwarded_port", guest: 8084, host: 8084, auto_correct: true  # Payment Service
    config.vm.network "forwarded_port", guest: 8085, host: 8085, auto_correct: true  # Loyalty Service
    config.vm.network "forwarded_port", guest: 8086, host: 8086, auto_correct: true  # Report Service
    config.vm.network "forwarded_port", guest: 15672, host: 15672, auto_correct: true  # RabbitMQ Management
    config.vm.network "forwarded_port", guest: 5672, host: 5672, auto_correct: true    # RabbitMQ AMQP
    
    
    manager.vm.provider "virtualbox" do |vb|
      vb.name = "manager01"
      vb.memory = "4024"
      vb.cpus = 1
    end

    manager.vm.synced_folder ".", "/vagrant"
    manager.vm.synced_folder "./monitoring-stack", "/home/vagrant/monitoring-stack"
    manager.vm.provision "shell", path: "manager.sh"
    manager.vm.provision "file", source: "docker-compose.yml", destination: "/home/vagrant/"
    #manager.vm.provision "file", source: "p.yaml", destination: "/home/vagrant/"
    #manager.vm.provision "file", source: "./nginx/nginx.conf", destination: "/home/vagrant/"

  end

  config.vm.define "worker01" do |worker1|
    worker1.vm.box = "ubuntu/jammy64"
    worker1.vm.hostname = "worker01"
    worker1.vm.network "private_network", ip: "192.168.56.51"
    worker1.vm.provider "virtualbox" do |vb|
      vb.name = "worker01"
      vb.memory = "2024"
      vb.cpus = 1
    end

    worker1.vm.provision "shell", path: "worker.sh"
    worker1.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define "worker02" do |worker2|
    worker2.vm.box = "ubuntu/jammy64"
    worker2.vm.hostname = "worker02"
    worker2.vm.network "private_network", ip: "192.168.56.52"
    worker2.vm.provider "virtualbox" do |vb|
      vb.name = "worker02"
      vb.memory = "2024"
      vb.cpus = 1
    end

    worker2.vm.provision "shell", path: "worker.sh"
    worker2.vm.synced_folder ".", "/vagrant"
  end
end


