server.port=8083

spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=5

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

gateway-service.uuid=b51ceda2-bfa5-11eb-8529-0242ac130003
booking-service.uuid=911ccb4c-c055-11eb-8529-0242ac130003

hotel-service.url=http://${HOTEL_SERVICE_HOST}:${HOTEL_SERVICE_PORT}/api/v1/hotels
payment-service.url=http://${PAYMENT_SERVICE_HOST}:${PAYMENT_SERVICE_PORT}/api/v1/payments
loyalty-service.url=http://${LOYALTY_SERVICE_HOST}:${LOYALTY_SERVICE_PORT}/api/v1/loyalty


#messagequeue
queue.name=${RABBIT_MQ_QUEUE_NAME}
#messagequeue-exchange
fanout.exchange=${RABBIT_MQ_EXCHANGE}
spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}
#guest
spring.rabbitmq.username=${RABBIT_MQ_USER}
#guest
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}


spring.config.import=optional:file:/app/config/jwt-keys.properties

management.endpoints.web.exposure.include=* 
management.endpoint.prometheus.enabled=true
