{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secrets
  labels:
    {{- include "hotel-booking-app.labels" . | nindent 4 }}
type: Opaque
data:
  GATEWAY_SERVICE_UUID: {{ .Values.secrets.authSecrets.data.GATEWAY_SERVICE_UUID | b64enc | quote }}
  BOOKING_SERVICE_UUID: {{ .Values.secrets.authSecrets.data.BOOKING_SERVICE_UUID | b64enc | quote }}
{{- end }}
