{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "hotel-booking-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.dbSecret.data.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbSecret.data.POSTGRES_PASSWORD | b64enc | quote }}
{{- end }}
