{{- if .Values.payment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-payment-service
  labels:
    {{- include "hotel-booking-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.payment.service.type }}
  selector:
    app: payment-service
  ports:
  - port: {{ .Values.payment.service.port }}
    targetPort: {{ .Values.payment.service.targetPort }}
    protocol: TCP
{{- end }}
