Vagrant.configure("2") do |config|
  # Общие настройки для всех машин
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Общий провижининг для ВСЕХ машин
  config.vm.provision "shell", inline: <<-SHELL
    # Включаем парольную аутентификацию SSH
    sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart ssh
  SHELL

  # Manager машина
  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.10"
  end

  # Node01 машина
  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.56.11"
    node01.vm.network "forwarded_port", guest: 80, host: 8080
    node01.vm.network "forwarded_port", guest: 8081, host: 8081
    node01.vm.network "forwarded_port", guest: 8082, host: 8082
    node01.vm.network "forwarded_port", guest: 8083, host: 8083
    node01.vm.network "forwarded_port", guest: 8087, host: 8087
    node01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Увеличиваем до 2GB
    end
  end

  # Node02 машина
  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.56.12"
  end
end
