apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: bettycon/booking:3.0
        ports:
        - containerPort: 8083
        env:
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/reservations_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_USER
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_PASSWORD
        - name: RABBIT_MQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_QUEUE_NAME
        - name: RABBIT_MQ_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_EXCHANGE
        - name: HOTEL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_HOST
        - name: HOTEL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_PORT
        - name: PAYMENT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_HOST
        - name: PAYMENT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_PORT
        - name: LOYALTY_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_HOST
        - name: LOYALTY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_PORT
        - name: BOOKING_SERVICE_UUID
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: BOOKING_SERVICE_UUID
        - name: GATEWAY_SERVICE_UUID
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: GATEWAY_SERVICE_UUID
