apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gatewayService.image.repository }}:{{ .Values.gatewayService.image.tag }}"
        env:
        - name: SESSION_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERVICE_HOST
        - name: SESSION_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERVICE_PORT
        - name: HOTEL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_HOST
        - name: HOTEL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_PORT
        - name: BOOKING_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_HOST
        - name: BOOKING_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_PORT
        - name: PAYMENT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_HOST
        - name: PAYMENT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_PORT
        - name: LOYALTY_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_HOST
        - name: LOYALTY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_PORT
        - name: REPORT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REPORT_SERVICE_HOST
        - name: REPORT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REPORT_SERVICE_PORT
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - port: 8087
    targetPort: 8087
