{{- if .Values.ingress.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: session-service
                port:
                  number: 8081
          - path: /api/v1/gateway
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8087
{{- end }}