apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-deployment
  labels:
    app: loyalty
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      containers:
      - name: loyalty
        image: "{{ .Values.loyaltyService.image.repository }}:{{ .Values.loyaltyService.image.tag }}"
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB_BALANCES
        - name: RABBIT_MQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_HOST
        - name: RABBIT_MQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_PORT
        - name: RABBIT_MQ_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_USER
        - name: RABBIT_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_PASSWORD
        - name: RABBIT_MQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_QUEUE_NAME
        - name: RABBIT_MQ_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_EXCHANGE
        volumeMounts:
        - name: jwt-keys
          mountPath: /app/config/jwt-keys.properties
          subPath: jwt-keys.properties
        ports:
        - containerPort: 8085
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-file-secret
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
spec:
  selector:
    app: loyalty
  ports:
  - port: 8085
    targetPort: 8085
