apiVersion: v1
kind: Secret
metadata:
  name: jwt-file-secret
type: Opaque
stringData:
  jwt-keys.properties: |
    privateKey={{ .Values.secrets.privateKey }}
    publicKey={{ .Values.secrets.publicKey }}
