apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.database.password | quote }}
  RABBIT_MQ_USER: {{ .Values.global.rabbitmq.user | quote }}
  RABBIT_MQ_PASSWORD: {{ .Values.global.rabbitmq.password | quote }}
  PUBLICKEY: |
{{ .Values.secrets.publicKey | nindent 4 }}
  PRIVATEKEY: |
{{ .Values.secrets.privateKey | nindent 4 }}
