gitlabUrl: "https://git.21-school.ru/"
runnerRegistrationToken: "GR1348941c7VXKdm_AAiRoLxYg8ey"

runners:
  config: |
    [[runners]]
      name = "kubernetes-runner"
      url = "https://git.21-school.ru/"
      token = "{{.RegistrationToken}}"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "docker:stable"
        privileged = true
        memory_limit = "1Gi"  
        cpu_limit = "1"
        service_memory_limit = "128Mi"  
        service_cpu_limit = "200m"
        helper_memory_limit = "128Mi"
        helper_cpu_limit = "200m"
        service_account = "gitlab-runner"  # ⬅️ ДОБАВЛЯЕМ ЭТУ СТРОКУ!
        [[runners.kubernetes.volumes.empty_dir]]
          name = "docker-certs"
          mount_path = "/certs/client"
          medium = "Memory"

rbac:
  create: true  

serviceAccount:
  create: true
  name: gitlab-runner

namespace: gitlab-runner
