stages:
  - build
  - test
  - staging

variables:
  DOCKER_HUB_USERNAME: "bettycon"
  PROJECT_NAME: "school21"

build:
  stage: build
  timeout: 2 hours
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature_/
      changes:
        - src/services/**/*
        - src/services/*/Dockerfile
        - src/services/*/pom.xml
      when: on_success
    - if: $CI_COMMIT_BRANCH =~ /^feature_/
      when: manual
      allow_failure: true
  before_script:
    - echo "ZGNrcl9wYXRfbWlrWHBtY1dIdVJnaE5lTUg0SWZ3TFlVM21nCg==" | base64 -d | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - cd src/services
    - |
      for service in session-service hotel-service booking-service payment-service loyalty-service report-service gateway-service; do
        if [ -d "$service" ] && [ -f "$service/Dockerfile" ]; then
          echo "=== Building $service ==="
          docker build -t $DOCKER_HUB_USERNAME/$PROJECT_NAME:$service-$CI_COMMIT_SHA ./$service
          docker push $DOCKER_HUB_USERNAME/$PROJECT_NAME:$service-$CI_COMMIT_SHA
          echo "=== $service completed ==="
        else
          echo "=== Skipping $service - directory or Dockerfile not found ==="
        fi
      done
      
      if [ -d "database" ] && [ -f "database/Dockerfile" ]; then
        echo "=== Building database ==="
        docker build -t $DOCKER_HUB_USERNAME/$PROJECT_NAME:database-$CI_COMMIT_SHA ./database
        docker push $DOCKER_HUB_USERNAME/$PROJECT_NAME:database-$CI_COMMIT_SHA
      fi
  after_script:
    - sleep 10

test:
  stage: test
  needs: ["build"]
  image: dtzar/helm-kubectl:latest
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature_/
  script:
    - NAMESPACE="ci-manual-$CI_COMMIT_SHA"
    - kubectl create namespace "$NAMESPACE" || true
    - cd src/hotel-booking-system
    
    - helm upgrade --install test-deploy . --namespace "$NAMESPACE" --set ingress.enabled=false --set bookingService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set bookingService.image.tag="booking-service-$CI_COMMIT_SHA" --set gatewayService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set gatewayService.image.tag="gateway-service-$CI_COMMIT_SHA" --set hotelService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set hotelService.image.tag="hotel-service-$CI_COMMIT_SHA" --set loyaltyService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set loyaltyService.image.tag="loyalty-service-$CI_COMMIT_SHA" --set paymentService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set paymentService.image.tag="payment-service-$CI_COMMIT_SHA" --set reportService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set reportService.image.tag="report-service-$CI_COMMIT_SHA" --set sessionService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set sessionService.image.tag="session-service-$CI_COMMIT_SHA" --set database.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set database.image.tag="database-$CI_COMMIT_SHA" --set rabbitmq.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set rabbitmq.image.tag="rabbitmq-$CI_COMMIT_SHA" --timeout 10m
    
    - sleep 400
    
    - kubectl get pods -n "$NAMESPACE" -o wide
    
    - apk add --no-cache nodejs npm
    - npm install -g newman
    
    - newman run application_tests.postman_collection.json --environment ci-environment.json --insecure || echo "Тесты завершились"
    
   after_script:
    - NAMESPACE="ci-manual-$CI_COMMIT_SHA"
    - kubectl delete namespace "$NAMESPACE" --wait=false || true

staging:
  stage: staging
  image: dtzar/helm-kubectl:latest
  when: manual
  only:
    - tags
  script:
    - NAMESPACE="staging-$(echo "$CI_COMMIT_TAG" | sed 's/\./-/g')"
    - kubectl create namespace "$NAMESPACE" || true
    - cd src/hotel-booking-system
    - helm upgrade --install staging-deploy . --namespace "$NAMESPACE" --set ingress.enabled=true --set ingress.host="staging-${CI_COMMIT_TAG}.hotel.local" --set bookingService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set bookingService.image.tag="booking-service-$CI_COMMIT_SHA" --set gatewayService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set gatewayService.image.tag="gateway-service-$CI_COMMIT_SHA" --set hotelService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set hotelService.image.tag="hotel-service-$CI_COMMIT_SHA" --set loyaltyService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set loyaltyService.image.tag="loyalty-service-$CI_COMMIT_SHA" --set paymentService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set paymentService.image.tag="payment-service-$CI_COMMIT_SHA" --set reportService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set reportService.image.tag="report-service-$CI_COMMIT_SHA" --set sessionService.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set sessionService.image.tag="session-service-$CI_COMMIT_SHA" --set database.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set database.image.tag="database-$CI_COMMIT_SHA" --set rabbitmq.image.repository="$DOCKER_HUB_USERNAME/$PROJECT_NAME" --set rabbitmq.image.tag="rabbitmq-$CI_COMMIT_SHA" --timeout 10m
    - sleep 60
    - kubectl get pods -n "$NAMESPACE"
    - kubectl get svc -n "$NAMESPACE"
  after_script:
    - echo "Staging deployment completed"

