server.port=8084

spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=5

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

gateway-service.uuid=b51ceda2-bfa5-11eb-8529-0242ac130003
booking-service.uuid=911ccb4c-c055-11eb-8529-0242ac130003

spring.config.import=optional:file:/app/config/jwt-keys.properties

management.endpoints.web.exposure.include=* 
management.endpoint.prometheus.enabled=true
